/**
 * Application-wide role constants.
 * SUPER_ADMIN can only be created via seed script, never via API.
 */
export const ROLES = Object.freeze({
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  ACCOUNTANT: "ACCOUNTANT",
  FACULTY: "FACULTY",
  PARENT: "PARENT",
  STUDENT: "STUDENT",
});

/**
 * Roles that can be assigned via API by Super Admin.
 * Super Admin is intentionally excluded — managed manually only.
 */
export const ASSIGNABLE_ROLES = Object.freeze([
  ROLES.ADMIN,
  ROLES.ACCOUNTANT,
  ROLES.FACULTY,
  ROLES.PARENT,
  ROLES.STUDENT,
]);

/**
 * User account statuses.
 */
export const USER_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  SUSPENDED: "SUSPENDED",
  DELETED: "DELETED",
});

/**
 * Permission keys used across the RBAC permission matrix.
 */
export const PERMISSIONS = Object.freeze({
  // User Management
  CREATE_USER: "CREATE_USER",
  READ_USER: "READ_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  CHANGE_USER_ROLE: "CHANGE_USER_ROLE",
  RESET_USER_PASSWORD: "RESET_USER_PASSWORD",
  MANAGE_USER_STATUS: "MANAGE_USER_STATUS",

  // Academic
  MANAGE_CLASSES: "MANAGE_CLASSES",
  MANAGE_SECTIONS: "MANAGE_SECTIONS",
  MANAGE_SUBJECTS: "MANAGE_SUBJECTS",
  MANAGE_ACADEMIC_SESSIONS: "MANAGE_ACADEMIC_SESSIONS",

  // Attendance
  MARK_ATTENDANCE: "MARK_ATTENDANCE",
  VIEW_ATTENDANCE: "VIEW_ATTENDANCE",
  VIEW_OWN_ATTENDANCE: "VIEW_OWN_ATTENDANCE",
  VIEW_CHILD_ATTENDANCE: "VIEW_CHILD_ATTENDANCE",

  // Assignments
  CREATE_ASSIGNMENT: "CREATE_ASSIGNMENT",
  VIEW_ASSIGNMENT: "VIEW_ASSIGNMENT",
  SUBMIT_ASSIGNMENT: "SUBMIT_ASSIGNMENT",
  GRADE_ASSIGNMENT: "GRADE_ASSIGNMENT",

  // Exams & Results
  CREATE_EXAM: "CREATE_EXAM",
  VIEW_EXAM: "VIEW_EXAM",
  ENTER_RESULTS: "ENTER_RESULTS",
  VIEW_RESULTS: "VIEW_RESULTS",
  VIEW_OWN_RESULTS: "VIEW_OWN_RESULTS",
  VIEW_CHILD_RESULTS: "VIEW_CHILD_RESULTS",

  // Fee Management
  CREATE_FEE: "CREATE_FEE",
  VIEW_FEE: "VIEW_FEE",
  RECORD_PAYMENT: "RECORD_PAYMENT",
  VIEW_OWN_FEE: "VIEW_OWN_FEE",
  VIEW_CHILD_FEE: "VIEW_CHILD_FEE",

  // Learning Materials
  UPLOAD_LECTURE: "UPLOAD_LECTURE",
  VIEW_LECTURE: "VIEW_LECTURE",
  CREATE_QUIZ: "CREATE_QUIZ",
  TAKE_QUIZ: "TAKE_QUIZ",
  VIEW_QUIZ_RESULTS: "VIEW_QUIZ_RESULTS",

  // Communication
  SEND_BROADCAST: "SEND_BROADCAST",
  MANAGE_NOTIFICATIONS: "MANAGE_NOTIFICATIONS",

  // Documents
  GENERATE_CERTIFICATE: "GENERATE_CERTIFICATE",
  GENERATE_FEE_VOUCHER: "GENERATE_FEE_VOUCHER",
  GENERATE_RECEIPT: "GENERATE_RECEIPT",
  GENERATE_ID_CARD: "GENERATE_ID_CARD",

  // Analytics
  VIEW_ANALYTICS: "VIEW_ANALYTICS",
  VIEW_FINANCIAL_ANALYTICS: "VIEW_FINANCIAL_ANALYTICS",
});

/**
 * Enterprise RBAC permission matrix.
 * Maps each role to its allowed set of permissions.
 */
export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS), // Full access

  [ROLES.ADMIN]: [
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.READ_USER,
    PERMISSIONS.UPDATE_USER,
    PERMISSIONS.DELETE_USER,
    PERMISSIONS.RESET_USER_PASSWORD,
    PERMISSIONS.MANAGE_USER_STATUS,
    PERMISSIONS.MANAGE_CLASSES,
    PERMISSIONS.MANAGE_SECTIONS,
    PERMISSIONS.MANAGE_SUBJECTS,
    PERMISSIONS.MANAGE_ACADEMIC_SESSIONS,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_ASSIGNMENT,
    PERMISSIONS.GRADE_ASSIGNMENT,
    PERMISSIONS.CREATE_EXAM,
    PERMISSIONS.VIEW_EXAM,
    PERMISSIONS.ENTER_RESULTS,
    PERMISSIONS.VIEW_RESULTS,
    PERMISSIONS.VIEW_FEE,
    PERMISSIONS.VIEW_LECTURE,
    PERMISSIONS.CREATE_QUIZ,
    PERMISSIONS.VIEW_QUIZ_RESULTS,
    PERMISSIONS.SEND_BROADCAST,
    PERMISSIONS.MANAGE_NOTIFICATIONS,
    PERMISSIONS.GENERATE_CERTIFICATE,
    PERMISSIONS.GENERATE_FEE_VOUCHER,
    PERMISSIONS.GENERATE_RECEIPT,
    PERMISSIONS.GENERATE_ID_CARD,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_FINANCIAL_ANALYTICS,
  ],

  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.READ_USER,
    PERMISSIONS.CREATE_FEE,
    PERMISSIONS.VIEW_FEE,
    PERMISSIONS.RECORD_PAYMENT,
    PERMISSIONS.GENERATE_FEE_VOUCHER,
    PERMISSIONS.GENERATE_RECEIPT,
    PERMISSIONS.VIEW_FINANCIAL_ANALYTICS,
  ],

  [ROLES.FACULTY]: [
    PERMISSIONS.READ_USER,
    PERMISSIONS.MARK_ATTENDANCE,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.CREATE_ASSIGNMENT,
    PERMISSIONS.VIEW_ASSIGNMENT,
    PERMISSIONS.GRADE_ASSIGNMENT,
    PERMISSIONS.CREATE_EXAM,
    PERMISSIONS.VIEW_EXAM,
    PERMISSIONS.ENTER_RESULTS,
    PERMISSIONS.VIEW_RESULTS,
    PERMISSIONS.UPLOAD_LECTURE,
    PERMISSIONS.VIEW_LECTURE,
    PERMISSIONS.CREATE_QUIZ,
    PERMISSIONS.VIEW_QUIZ_RESULTS,
  ],

  [ROLES.PARENT]: [
    PERMISSIONS.VIEW_CHILD_ATTENDANCE,
    PERMISSIONS.VIEW_ASSIGNMENT,
    PERMISSIONS.VIEW_CHILD_RESULTS,
    PERMISSIONS.VIEW_CHILD_FEE,
    PERMISSIONS.VIEW_LECTURE,
  ],

  [ROLES.STUDENT]: [
    PERMISSIONS.VIEW_OWN_ATTENDANCE,
    PERMISSIONS.VIEW_ASSIGNMENT,
    PERMISSIONS.SUBMIT_ASSIGNMENT,
    PERMISSIONS.VIEW_OWN_RESULTS,
    PERMISSIONS.VIEW_OWN_FEE,
    PERMISSIONS.VIEW_LECTURE,
    PERMISSIONS.TAKE_QUIZ,
  ],
});
